name: casync # you probably want to 'snapcraft register <name>'
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Content-Addressable Data Synchronization Tool # 79 char long summary
description: |
  casync is
  1. A combination of the rsync algorithm and content-addressable storage
  2. An efficient way to store and retrieve multiple related versions of large
     file systems or directory trees
  3. An efficient way to deliver and update OS, VM, IoT and container images 
     over the Internet in an HTTP and CDN friendly way
  4. An efficient backup system
  
  casync uses well-known concepts implemented in a variety of other projects
  (primarily git and rsync), and puts them together in a moderately new, nice way

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: classic # use 'strict' once you have the right plugs and slots

apps:
  casync:
    command: /usr/bin/casync
    plugs: [network]

parts:
  casync:
    # See 'snapcraft plugins'
    plugin: meson #you may need backport archives, e.g., xenial-backports/universe
    source: https://github.com/systemd/casync.git
    source-type: git
    build-packages:
      - liblzma-dev
      - libcurl4-gnutls-dev
      - libgcrypt-dev
      - libacl1-dev
      - libfuse-dev
      - rsync
